config/routes.rb
Rails.application.routes.draw do
  

  get 'dashboard/index'

  get 'dashboard/show'

  devise_for :users

 root 'welcome#index'
get '/faqs' => 'welcome#faqs'
resources :paperedits do 
  resources :papercuts
  resources :lines
end

  resources :transcripts do
  resources :lines
end

resources :lines

resources :blog

resources :dashboard

post 'save_paper_edit/' => 'papercuts#save_paper_edit'

 get 'paperedits/:id/clear_all/' => 'papercuts#clear_all'

end

app/models/line.rb
class Line < ActiveRecord::Base
  require 'csv'
  belongs_to :transcript
  has_many :papercuts
  has_many :paperedits, through: :papercuts
  accepts_nested_attributes_for :papercuts, :paperedits


  def self.to_csv
  # raise "Kapow!!!"
  

  CSV.generate do |csv|
    csv << ["N","L", "Tc in","Tc out", "Speaker","Text", "Keywords", "Notes", "File name", "Reel","Filming date"]
    rec_in = Timecode.parse("00:00:00:00",fps = 25)
    all.order("position asc").each do |line|
      tc_meta = Timecode.parse(line.transcript.tc_meta, fps = 25)
      time_in = Timecode.parse_with_fractional_seconds(line.tc_in, fps = 25) 
      time_out = Timecode.parse_with_fractional_seconds(line.tc_out, fps = 25)
      rec_out =  time_out - time_in + rec_in
      csv << [line.papercuts.first.position,line.n, time_in , time_out , line.transcript.speakername, line.text, line.tag, line.note, line.transcript.filename,line.transcript.reel, line.transcript.date ]
    rec_in = rec_out
    end #closes loop
  end #closes csv
end # end of method self csv


# def self.format_lines
#    all.order("position asc").each do |line|
#     "hello world"
#   end
# end 


# def self.to_text
#   all.order("position asc").each do |line|
#   end
# end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /lines
  # GET /lines.json
  def index

    @transcript = Transcript.find(params[:transcript_id])
    # render plain: params.inspect
     @lines = @transcript.lines
     # render plain: @lines.inspect
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
    # render plain: params.inspect
    @transcript =  Transcript.find(params[:transcript_id])
    @line = Line.find(params[:id])
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render :show, status: :created, location: @line }
      else
        format.html { render :new }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to transcript_path(@line.transcript), notice: 'Line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:tc_in, :tc_out, :text, :n, :note, :tag, :transcript_id, :papercuts_attributes =>[:position])
    # not sure about :papercuts_attributes =>[:position]
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_for([@transcript, @line]) do |f| %>
  <% if @line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% @line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tc_in %><br>
    <%= f.text_field :tc_in %>
  </div>
  <div class="field">
    <%= f.label :tc_out %><br>
    <%= f.text_field :tc_out %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :n %><br>
    <%= f.number_field :n %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :transcript_id %><br>
    <%= f.text_field :transcript_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lines/edit.html.erb
<h1>Editing line</h1>

<%= render 'form' %>


<%= link_to 'Back', transcript_lines_path(@transcript) %>

app/views/lines/index.html.erb
<h1>Listing lines</h1>

<table>
  <thead>
    <tr>
       <th>N</th>
      <th>Tc in</th>
      <th>Tc out</th>
      <th>Text</th>
     
      <th>Note</th>
      <th>Tag</th>
      <th>Transcript</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.n %></td>
        <td><%= line.tc_in %></td>
        <td><%= line.tc_out %></td>
        <td><%= line.text %></td>
        <td><%= line.note %></td>
        <td><%= line.tag %></td>
        <td><%= line.transcript.name %></td>
       
        <td><%= link_to 'Edit', edit_transcript_line_path(@transcript,line) %></td>
        <td><%= link_to 'Destroy', transcript_line_path(@transcript, line), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lines/new.html.erb
<h1>New line</h1>

<%= render 'form' %>

<%= link_to 'Back', lines_path %>

app/views/lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tc in:</strong>
  <%= @line.tc_in %>
</p>

<p>
  <strong>Tc out:</strong>
  <%= @line.tc_out %>
</p>

<p>
  <strong>Text:</strong>
  <%= @line.text %>
</p>

<p>
  <strong>N:</strong>
  <%= @line.n %>
</p>

<p>
  <strong>Note:</strong>
  <%= @line.note %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @line.tag %>
</p>

<p>
  <strong>Transcript:</strong>
  <%= @line.transcript %>
</p>

<%= link_to 'Edit', edit_line_path(@line) %> |
<%= link_to 'Back', lines_path %>