config/routes.rb
Rails.application.routes.draw do
  

  get 'dashboard/index'

  get 'dashboard/show'

  devise_for :users

 root 'welcome#index'
get '/faqs' => 'welcome#faqs'
resources :paperedits do 
  resources :papercuts
  resources :lines
end

  resources :transcripts do
  resources :lines
end

resources :lines

resources :blog

resources :dashboard

post 'save_paper_edit/' => 'papercuts#save_paper_edit'

 get 'paperedits/:id/clear_all/' => 'papercuts#clear_all'

end

app/models/transcript.rb
class Transcript < ActiveRecord::Base
  has_many :lines, dependent: :destroy
  belongs_to :user


validates :filename, :speakername, :date, :youtubeurl, :reel, :tc_meta, :name, :presence => true

# validates_attachment :sbv_file, :presence => true

def read_sbv_file(sbv_file)

n = 0
state = :timecodes
tc_in = tc_out = nil
text_chunks = []

#m = 1  #setting transcript number, transcript_id for the lines, to be grouped into transcripts
sbv_file.read.split("\n").each do |line|
  line.gsub!(/\n/, '')
  case state
  when :timecodes
    tc_in, tc_out = line.split(',')
    n += 1
    state = :text
  when :text
    if line.empty?
      self.lines.create!(tc_in: "0"+tc_in.gsub(/\s+/, ""), tc_out: "0"+tc_out.gsub(/\s+/, ""), text: text_chunks.join(' ').force_encoding('UTF-8'), n: n)
      text_chunks = []
      state = :timecodes
    else
      text_chunks << line
    end
  end
end


end#end of method


def read_srt_file(srt_file)

n=0
#uisng this gem srt https://github.com/cpetersen/srt
file = SRT::File.parse(srt_file.read)
  file.lines.each do |line|
   n= line.sequence
   tc_in= line.time_str.split(/ --> /)[0].sub(",",".").match(/\d{2}:\d{2}:\d{2}\.\d{3}/).to_s.gsub(/\s+/, "")
   tc_out= line.time_str.split(/ --> /)[1 ].sub(",",".").match(/\d{2}:\d{2}:\d{2}\.\d{3}/).to_s.gsub(/\s+/, "")
   # enforcing Encoding to UTF-8 coz otherwise when copy and pasting from word to make the srt, risk of ASCII compatibility issues.
   text= line.text.join(' ').force_encoding('UTF-8') #.text is an srt method and it returns an array
    self.lines.create!(tc_in: tc_in, tc_out: tc_out, text: text, n: n)
  end


end#end of method srt


end#end of class

app/controllers/transcripts_controller.rb
class TranscriptsController < ApplicationController
  before_action :set_transcript, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!
 
  # GET /transcripts
  # GET /transcripts.json
  def index
    @user = current_user
    @transcripts = @user.transcripts

     # format.json { render json: @transcript.lines.to_json, status: :ok }
  end

  # GET /transcripts/1
  # GET /transcripts/1.json
  def show
    respond_to do |format|
      format.html   
      format.text { response.headers['Content-Disposition'] = "attachment; filename=transcript_#{ @transcript.name}_#{Time.now.strftime("%Y-%m-%d_%R")}.txt" }
      format.sbv { response.headers['Content-Disposition'] = "attachment; filename=transcript_#{ @transcript.name}_#{Time.now.strftime("%Y-%m-%d_%R")}.sbv" }
      format.srt { response.headers['Content-Disposition'] = "attachment; filename=transcript_#{ @transcript.name}_#{Time.now.strftime("%Y-%m-%d_%R")}.srt" }
  
    end
  end

  # GET /transcripts/new
  def new
     @user = current_user
    @transcript = @user.transcripts.new(:date => Time.now.strftime("%d/%m/%Y"), :youtubeurl => "http://youtu.be/")

  end

  # GET /transcripts/1/edit
  def edit
  end

  # POST /transcripts
  # POST /transcripts.json
  def create
  # render plain: params[:sbv_file].original_filename.inspect
    @user = current_user
    @transcript =  @user.transcripts.create(transcript_params)

    # if TRANSCRIPT IF SBV CALLL SBV METHOD
    if params[:sbv_file].original_filename.split(".")[1]=="sbv"
      @transcript.read_sbv_file(params[:sbv_file])
    

 # IF TRANSCRIPT IS SRT CALL SRT METHOD
  elsif params[:sbv_file].original_filename.split(".")[1]=="srt"
     @transcript.read_srt_file(params[:sbv_file])

     # render plain: params[:sbv_file].original_filename.inspect

  end#end if

    respond_to do |format|
      if @transcript.save
        format.html { redirect_to @transcript, notice: 'Transcript was successfully created.' }
        format.json { render :show, status: :created, location: @transcript }
         # intercom_custom_data.user['Created_New_Transcript'] = Time.now
      else
        format.html { render :new }
        format.json { render json: @transcript.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transcripts/1
  # PATCH/PUT /transcripts/1.json
  def update
    # render plain: params[:id].inspect
    @user = current_user
    @transcript =  @user.transcripts.find( params[:id])

    respond_to do |format|
      if @transcript.update(transcript_params)
        format.html { redirect_to @transcript, notice: 'Transcript was successfully updated.' }
        format.json { render :show, status: :ok, location: @transcript }
      else
        format.html { render :edit }
        format.json { render json: @transcript.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transcripts/1
  # DELETE /transcripts/1.json
  def destroy
    @transcript.destroy
    respond_to do |format|
      format.html { redirect_to transcripts_url, notice: 'Transcript was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transcript
       @user = current_user
    @transcript =  @user.transcripts.find(params[:id])
      # @transcript = Transcript.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transcript_params
      params.require(:transcript).permit(:filename, :speakername, :date, :youtubeurl, :reel, :tc_meta,:name)
    end
end

app/helpers/transcripts_helper.rb
module TranscriptsHelper
end

app/views/transcripts/_form.html.erb
<%= form_for(@transcript, html: {multipart: true}) do |f| %>
  <% if @transcript.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transcript.errors.count, "error") %> prohibited this transcript from being saved:</h2>

      <ul>
      <% @transcript.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :transcript_name %><br>
    <%= f.text_field :name,  placeholder:"Interview with...",class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= f.label :sbv_file %><br>
    <%= file_field_tag :sbv_file , class: 'form-control' %>
    <span class="help-block">.sbv or .srt transcription file, ie from youtube captioning</span>
  </div>
  <div class="field">
    <%= f.label :speakername %><br>
    <%= f.text_field :speakername, placeholder:"What is the name of the person interviewed?", class: 'form-control'  %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, class: 'form-control' %>
    <span class="help-block">You can check in the metadata of the clip for this too. dd/mm/yyyy</span>
  </div>
  <div class="field">
    <%= f.label :youtubeurl %><br>
    <%= f.text_field :youtubeurl, class: 'form-control' %>
     <span class="help-block">The URL where you uploaded the video to get the youtube captions, needed to show you a preview of the paperedit</span>
  </div>
  
  <br>
  <hr>
<h4>Camera Metadata<a type="button" class="btn btn-link" data-toggle="modal" data-target="#myModal"> ?</a></h4>

    <div class="field">
    <%= f.label :filename %>
<!-- Button trigger modal -->
<a type="button" class="btn btn-link" data-toggle="modal" data-target="#myModal">  ?</a>
    <br>
    <%= f.text_field :filename , placeholder:"ie XF5001.mov", class: 'form-control' %>
    <span class="help-block">File name of the transcribed video</span>
  </div>
  <div class="field">
    <%= f.label :reel %>
<!-- Button trigger modal -->
<a type="button" class="btn btn-link" data-toggle="modal" data-target="#myModal">  ?</a>
    <br>
    <%= f.text_field :reel, class: 'form-control' %>
       <span class="help-block">Metada of the Card name, you can use fcp or another editing software to find this out. You might have changed this name while backing up, transcoding, ie if using canon xf utility</span>
  </div>
  <div class="field">
    <%= f.label :Media_start %>
<!-- Button trigger modal -->
<a type="button" class="btn btn-link" data-toggle="modal" data-target="#myModal">  ?</a>
    <br>
    <%= f.text_field :tc_meta, class: 'form-control' %> 
    <span class="help-block">Start timecode in the metadata of the video file ie. the timecode of the video in the editing software might not start at <code>00:00:00:00</code> but for example at <code>00:49:04:20</code>, depending on how the timecodes where recorded in the camera, ie rec run, free run etc..</span>
  </div>
  <div class="actions">
    
    <%= f.button 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>


<!-- modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Where to find your file's <code>Camera Metadata</code></h4>
      </div>
      <div class="modal-body">
        
<p>We need the <code>filename</code>, <code>reel</code> and <code>Media Start</code> as it appears in the metadata of the video file.</p>

<p>For instance In Final Cut Pro 7</p>
<p>1. Find the clip in the inspector view, top left panel</p>
<p>2. Rigth click the clip in the inspector view, top left panel</p>
<p>3. Choose <code> item proprieties</code> -> <code>logging info</code></p>

<%= image_tag "loggingInfo.png", class: "img-responsive" %>
<p>4. in the <code>logging</code> tab, you'll find the first 3 fields are <code>Name</code>(filename), <code>Reel</code> and <code>Media Start</code></p>
<%= image_tag "fileNameReelNameMediaStart.png", class: "img-responsive" %>

<p>5. The only adjustment to make is that for the filename <code>Name</code> we need it with the <code>.mov</code> extension.</p> 

<p>For instance if I were to take the file <code>Name</code> from the example it would be <code>CC027_01.mov</code> </p>

<p>6. If the <code>Reel</code> name is blank, which could be for a number of reasons, such as working with footage from the Internet, or DSLRs, then in this field you can add a reel name, and it will prompt you to save it to disk, and write the metadata onto the actual file. </p><p>To use autoEdi, your video file needs to have a reel name, otherwise the exported EDL will not be have enough informations on it to be able to reconnect the sequence in the editing software of choie.</p> 
<br>
<p>For any questions: 
<a href="mailto:info@autoedit.io?subject=autoEdit%20Metadata%20Enquiry
&body=Hello,%0D%0A I am trying to upload a transcript in autoEdit and I am having trouble with identifying the metadata..">info@autoedit.io</a></p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

app/views/transcripts/edit.html.erb
<legend>Edit Transcript</legend>

<%= render 'form' %>
<br>
<%= link_to 'Back', transcripts_path, class: 'btn btn-default btn' %>
<%= link_to 'Show', @transcript, class: 'btn btn-info' %> 

app/views/transcripts/index.html.erb
<h2>Transcripts  <%= link_to 'New Transcript', new_transcript_path, class: "btn btn-warning btn-xs"  %>
</h2>


<div class="row">
<div class="col-6">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed table-responsive">
  <tr>
    <th> Name  </th>
     <th> Speaker  </th>
    <th> File  </th>
    <th> Fate</th>
    <th> YouTube </th>
    <th> Text</th>
    <th> Lines </th>
    <th> Words</th>
    <th> Reading time</th>
    <th> Transcribed speech duration</th>
    <th> File duration</th>
    <th> </th>
    <th> </th>
    <th> </th>

    </tr>



    <% @transcripts.each do |t| %>
  <% a =[]  %>
<td><%= link_to "#{t.name}", transcript_path(t),  class: "btn btn-link" %></td>
    <td><%= link_to "#{t.speakername}", transcript_path(t),  class: "btn btn-link" %></td>
     <td><%= t.filename %></td>
    <td><%= t.date  %> </td>

<td> 
 <%= link_to "Youtube", "#{t.youtubeurl}", :target => "_blank",  class: "btn btn-info btn-xs"%>

</td>
    <td><%= t.lines.first.text[0..10] if t.lines.any? %> [...] </td>
    <td><%= t.lines.count %></td>
  <td><%= t.lines.map(&:text).to_s.scan(/\w+/).size %></td>
     <% word_count =  t.lines.map(&:text).to_s.scan(/\w+/).size %>
<td> <%= (word_count / 100.0).ceil %> minutes</td>

      <% c=[] %>
 <% t.lines.each do |l| %>
  <% time_in = Timecode.parse_with_fractional_seconds(l.tc_in, fps = 25) %>
<% time_out = Timecode.parse_with_fractional_seconds(l.tc_out, fps = 25) %>
<% c << time_out - time_in  %>
       <% end %>
<%= a.uniq.to_csv %>
     <td><%= c.sum %></td>

      <% last_time_out = Timecode.parse_with_fractional_seconds(t.lines.last.tc_out , fps = 25) if t.lines.last %>
  <td><%= last_time_out   %> </td>
    <td><%= link_to "show", transcript_path(t),  class: "btn btn-info btn-xs" %></td>
 <td><%= link_to "edit", edit_transcript_path(t), class: "btn btn-success btn-xs"  %></td>
  <td><%= link_to 'Delete', transcript_path(t),  class: "btn btn-primary btn-xs",
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>

</tr>
<% end %>
</table>
</div>
</div>
</div>

app/views/transcripts/new.html.erb
<legend>New Transcript</legend>

<%= render 'form' %>
<br>
<%= link_to 'Back', transcripts_path, class: 'btn btn-default btn' %>

app/views/transcripts/show.html.erb
<!--  make table searchable -->
<!-- from http://jsfiddle.net/giorgitbs/52aK9/1/ -->
<script type="text/javascript" charset="utf-8">
$(document).ready(function () {

    (function ($) {

        $('#filter').keyup(function () {

            var rex = new RegExp($(this).val(), 'i');
            $('.searchable tr').hide();
            $('.searchable tr').filter(function () {
                return rex.test($(this).text());
            }).show();

        })

    }(jQuery));

});

</script>


<!-- Best in place inline editing -->
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
  /* Activating Best In Place */
  jQuery(".best_in_place").best_in_place();
});
</script>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
<p>
  <strong>File name:</strong>
   <%= best_in_place @transcript, :filename %>
 
</p>

<p>
  <strong>Speaker name:</strong>
     <%= best_in_place @transcript, :speakername %>
  
</p>

<p>
  <strong>Date:</strong>
   <%= best_in_place @transcript, :date %>
 
</p>

<p>
  <strong>Youtube url:</strong>
  
  <%= link_to "#{@transcript.youtubeurl }",  @transcript.youtubeurl, :target => "_blank" %>

</p>

<p>
  <strong>Reel:</strong>
   <%= best_in_place @transcript, :reel %>
 
</p>

<p>
  <strong>Tc meta:</strong>
   <%= best_in_place @transcript, :tc_meta %>

</p>
<%= link_to "edit", edit_transcript_path(@transcript), class: "btn btn-success btn-xs"  %>
<hr>
 <p> <strong>Lines: </strong><%= @transcript.lines.count %> 
  <strong> Words: </strong><%= @transcript.lines.map(&:text).to_s.scan(/\w+/).size %></p>
     <% word_count =  @transcript.lines.map(&:text).to_s.scan(/\w+/).size %>
<p><strong>Reading Time: </strong><%= (word_count / 100.0).ceil %> minutes</p>

 <% c=[] %>
 <% @transcript.lines.each do |l| %>
  <% time_in = Timecode.parse_with_fractional_seconds(l.tc_in, fps = 25) %>
<% time_out = Timecode.parse_with_fractional_seconds(l.tc_out, fps = 25) %>
<% c << time_out - time_in  %>
       <% end %>
<p><strong>Transcribed speech: </strong><%= c.sum %></p>
      <% last_time_out = Timecode.parse_with_fractional_seconds(@transcript.lines.last.tc_out , fps = 25) if @transcript.lines.last %>
<p><strong>File duration: </strong><%= last_time_out   %></p>




</div> <!-- col -->


<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
<!--  show tags in this transcript -->
<h3> <small><span class="glyphicon glyphicon-tags" aria-hidden="true"></small> Tags</span> </h3>
<%  @arrayOfTags = []    %>
<% @transcript.lines.order("n asc").each do |line|  %>
<% if line.tag != nil then @arrayOfTags << line.tag end %>
<%  end    %>


<%  @hashOfTags = @arrayOfTags.sort { |w1, w2| w2.casecmp(w1) }.each_with_object(Hash.new(0)) { |word,counts| counts[word] += 1 } %>



<ul class="nav nav-pills">
  <%   @hashOfTags.each do |tag, count| %>
  <% if tag != ""  %>
  <li class="active"><%= tag %> <span class="badge"><%= count %></span></li>
  <% end %>
  <% end %>
</ul>

<!-- end of show tags -->


</div> <!-- col -->
</div> <!-- row -->




<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Transcript: <strong><%= @transcript.speakername %> | <%= @transcript.filename %></strong>
        <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Close</button></h4>
      </div>
      <div class="modal-body">
            <p><strong>  <%= @transcript.lines.order("n asc").map(&:text).to_s.scan(/\w+/).size  %> </strong>Words,
              <% c=[] %>
  <%  @transcript.lines.each do |l| %>
<% time_in = Timecode.parse_with_fractional_seconds(l.tc_in, fps = 25) %>
<% time_out = Timecode.parse_with_fractional_seconds(l.tc_out, fps = 25) %>
<% c << time_out - time_in  %>
       <% end %>
   <strong>  <%= c.sum %></strong> Duration </p></p>
<hr>
       <p> <% @transcript.lines.order("n asc").each do |l| %>
        <%= l.text %></p>
       <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

<!-- end of Modal  -->
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
<h2><strong>Transcript: </strong><%= best_in_place @transcript, :name %></h2>
</div> <!-- col -->
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
   <%= link_to raw("<span class='glyphicon glyphicon-align-justify' aria-hidden='true'> SBV</span>").html_safe, transcript_path(format: "sbv"), class: "btn btn-danger btn-xs disabled" %>
    <%= link_to raw("<span class='glyphicon glyphicon-align-justify' aria-hidden='true'> SRT</span>").html_safe, transcript_path(format: "srt"), class: "btn btn-danger btn-xs disabled" %>
  <%= link_to raw("<span class='glyphicon glyphicon-file' aria-hidden='true'> Text</span>").html_safe, transcript_path(format: "text"), class: "btn btn-danger btn-xs" %>
 <button class="btn btn-danger btn-xs" data-toggle="modal" data-target="#myModal"> 
   <span class="glyphicon glyphicon-file" aria-hidden="true"> Quick Text Preview</span>
</button>
</div> <!-- col -->
</div> <!-- row -->
<br>

<!-- search header  -->
<div class="input-group"> <span class="input-group-addon">
 <span class="glyphicon glyphicon-search" aria-hidden="true"> </span>
</span>

    <input id="filter" type="text" class="form-control" placeholder="Type here to search the trasncripts...ie #aTag">
</div>
<!-- end search header  -->
<table class="table table-striped table-hover table-condensed table-responsive">
  <thead>
    <tr>
       <th>N</th>
      <th>Tc in</th>
      <th>Tc out</th>
      <th>Text</th>
     
      <th>Note</th>
      <th><span class="glyphicon glyphicon-tag" aria-hidden="true"><strong>Tag</strong></span></th>
      <th>Transcript</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="searchable">
    <% @transcript.lines.order("n asc").each do |line| %>
      <tr                       
             <% if !line.tag.blank? %>
                        <%=  raw("class='warning'").html_safe %>
                       <% end %>

      >
        <td><%= line.n %></td>
        <td><%= best_in_place line, :tc_in %></td>
        <td><%= best_in_place  line, :tc_out %></td>
       
        <td>   <%= best_in_place @transcript.lines.find(line.id), :text, as: :textarea %></td>
      
     <td>   <%= best_in_place @transcript.lines.find(line.id), :note, as: :textarea  %></td>
        <td>   <%= best_in_place @transcript.lines.find(line.id), :tag %></td>
        <td><%= line.transcript.name %></td>
       
      
        <td><%= link_to 'Delete', transcript_line_path(@transcript, line),   class: "btn btn-primary btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/transcripts/show.sbv.erb
<% @transcript.lines.order("n asc").each do |l| %>
<%= <<-PARAGRAPH
#{Timecode.parse_with_fractional_seconds(l.tc_in, fps = 25).with_fractional_seconds()+"0"}, #{Timecode.parse_with_fractional_seconds(l.tc_out, fps = 25).with_fractional_seconds()+"0"}
#{l.text}

PARAGRAPH
%>
<% end %>

app/views/transcripts/show.srt.erb
<% n = 0%>
<% @transcript.lines.order("n asc").each do |l| %>
<%= <<-PARAGRAPH
#{n+=1 }
#{l.tc_in.sub(/\./,',')} --> #{l.tc_out.sub(/\./,',') }
#{l.text}
PARAGRAPH
%>
<% end %>

app/views/transcripts/show.text.erb
<%  n =0 %>
<%= "Transcript: '#{@transcript.name}' "%>
<%= "by: #{@user.email} "%>
<%= "Time: #{Time.now.strftime("%Y-%m-%d_%R")}"%>

Transcript "<%= @transcript.name %>"
Speaker: "<%= @transcript.speakername %>"
Date: "<%= @transcript.date %>"
File name: "<%= @transcript.filename %>"
Reel: "<%= @transcript.reel %>"

Lines: <%= @transcript.lines.count %>
Words: <%= @transcript.lines.map(&:text).to_s.scan(/\w+/).size %>
    	<% word_count =  @transcript.lines.map(&:text).to_s.scan(/\w+/).size %>
Reading Time: <%= (word_count / 100.0).ceil %> minutes
 <% c=[] %>
 <% @transcript.lines.each do |l| %>
  <% time_in = Timecode.parse_with_fractional_seconds(l.tc_in, fps = 25) %>
<% time_out = Timecode.parse_with_fractional_seconds(l.tc_out, fps = 25) %>
<% c << time_out - time_in  %>
       <% end %>
Transcribed speech: <%= c.sum %>
      <% last_time_out = Timecode.parse_with_fractional_seconds(@transcript.lines.last.tc_out , fps = 25) if @transcript.lines.last %>
File duration: <%= last_time_out   %>

<% rec_in = Timecode.parse("00:00:00:00",fps = 25) %>
 <% @transcript.lines.order("n asc").each do |l| %>
 <% tc_meta = Timecode.parse(l.transcript.tc_meta, fps = 25) %>
 <% time_in = Timecode.parse_with_fractional_seconds(l.tc_in, fps = 25) %>
<% time_out = Timecode.parse_with_fractional_seconds(l.tc_out, fps = 25) %>
 <% rec_out =  time_out - time_in + rec_in%>
<%  n += 1 %>
<% reel = l.transcript.reel.gsub(/_/,"") %>
<%= <<-PARAGRAPH
#{l.n}  #{time_in } #{time_out } #{l.transcript.speakername}: #{l.text}  #{if !l.tag.blank? then  l.tag else end }
PARAGRAPH
  %><% end %>
 <%= <<-PARAGRAPH
*Timecode reference relative to transcription file
beta.autoedit.io
  PARAGRAPH
  %>