config/routes.rb
Rails.application.routes.draw do
  

  get 'dashboard/index'

  get 'dashboard/show'

  devise_for :users

 root 'welcome#index'
get '/faqs' => 'welcome#faqs'
resources :paperedits do 
  resources :papercuts
  resources :lines
end

  resources :transcripts do
  resources :lines
end

resources :lines

resources :blog

resources :dashboard

post 'save_paper_edit/' => 'papercuts#save_paper_edit'

 get 'paperedits/:id/clear_all/' => 'papercuts#clear_all'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>autoEdit</title>
  <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<%= favicon_link_tag 'favicon.ico' %>

</head>
<body>



  <!--  Cosmo Nav bar -->
<div class="navbar navbar-default">
                  <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">autoEdit</a>
                  </div>
                  <div class="navbar-collapse collapse navbar-responsive-collapse">
                    <ul class="nav navbar-nav">

                    
                      <li><%= link_to raw("<span class='glyphicon glyphicon-align-justify' aria-hidden='true'> Transcripts</span>").html_safe, transcripts_path %></li>
                      <li><%= link_to raw("<span class='glyphicon glyphicon-film' aria-hidden='true'> Paper Edits</span>").html_safe, paperedits_path %></li>

                      
                      <li><%= link_to raw("<span class='glyphicon glyphicon-circle-arrow-up' aria-hidden='true'> New Transcript</span>").html_safe, new_transcript_path %></li>
                     
                      <li><%= link_to raw("<span class='glyphicon glyphicon-plus' aria-hidden='true'> New Paper Edit</span>").html_safe, new_paperedit_path %></li>
                    </ul>
                       <ul class="nav navbar-nav navbar-right">

                       
                        <li><%= link_to 'FAQs',  faqs_path, :class => 'navbar-link' %> </li>
                        <li><%= link_to 'Blog',  blog_index_path, :class => 'navbar-link' %> </li>
                        <li>
                          <a href="mailto:info@autoedit.io?subject=autoEdit%20Enquiry
&body=Hello,%0D%0A I have a quesiton about autoEdit..">Contact</a> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>  |  Logout
          <% else %>
            Sign in
          <% end %>
          
          <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <!-- user sign in / sign out -->
            <% if user_signed_in? %> .
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> </li>
            <% else %>
              <li> <%= link_to "Sign in", new_user_session_path, :class => 'navbar-link' %> </li>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> </li>
            <% end %>
          </ul>
        </li>
      </ul>
                  </div><!-- /.nav-collapse -->
              </div>
<!-- End of   Cosmo Nav bar -->
	<div class="container">

<!-- Devise notification -->
<% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
       <p class="alert alert-danger"><%= alert %></p>
     <% end %>
     <!-- devise flash notification end -->

		<%= yield %>

	</div>

<!--Start of Tawk.to Script-->
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var $_Tawk_API={},$_Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/54e3d2103fc587e101fea9a4/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
<!--End of Tawk.to Script-->



</body>
</html>